eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
        boot:
          autoconfigure: INFO
        cloud:
          gateway: DEBUG
          gateway.route:
            RouteDefinitionLocator: INFO
      springframework.web.client.RestTemplate: INFO
      reactor.netty: DEBUG

server:
  port: 8083
  netty:
    max-chunk-size: 314572800

spring:
  main:
    web-application-type: reactive
  application:
    name: astromyllc-api-gateway
  codec:
    max-in-memory-size: 314572800
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      httpclient:
        max-header-size: 314572800
        response-timeout: 300s
      default-filters:
        - name: RequestSize
          args:
            maxSize: 314572800
      routes:
        - id: setup
          uri: lb://shootingStar-setup
          predicates:
            - Path=/api/setup/**
          filters:
            - name: RequestSize
              args:
                maxSize: 314572800

        - id: online-application
          uri: lb://online-application
          predicates:
            - Path=/api/applications/**
          filters:
            - name: RequestSize
              args:
                maxSize: 314572800

        - id: HR
          uri: lb://HR-Service
          predicates:
            - Path=/api/hr/**
          filters:
            - name: RequestSize
              args:
                maxSize: 314572800

        - id: finance
          uri: lb://finance
          predicates:
            - Path=/api/finance/**
          filters:
            - name: RequestSize
              args:
                maxSize: 314572800

        - id: clinic
          uri: lb://clinic
          predicates:
            - Path=/api/clinic/**
          filters:
            - name: RequestSize
              args:
                maxSize: 314572800

        - id: stores-inventory
          uri: lb://stores-inventory
          predicates:
            - Path=/api/stores_inventory/**
          filters:
            - name: RequestSize
              args:
                maxSize: 314572800

        - id: academics
          uri: lb://shootingStar-academics
          predicates:
            - Path=/api/academics/**
          filters:
            - name: RequestSize
              args:
                maxSize: 314572800

        - id: administration-pta
          uri: lb://administration-pta
          predicates:
            - Path=/api/administration-pta/**
          filters:
            - name: RequestSize
              args:
                maxSize: 314572800

        - id: accommodation
          uri: lb://accommodation
          predicates:
            - Path=/api/accommodation/**
          filters:
            - name: RequestSize
              args:
                maxSize: 314572800

        - id: discovery_server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery_server_static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: astro_orb
          uri: http://localhost:7013
          predicates:
            - Path=/astro_orb/web
          filters:
            - SetPath=/
            - name: RequestSize
              args:
                maxSize: 314572800

        - id: astro_orb_static
          uri: http://localhost:7013
          predicates:
            - Path=/orb/**

  sleuth:
    sampler:
      probability: 1.0