

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true


logging:
  level:
    root: INFO
    org:
      springframework:
        security=DEBUG:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO

server:
  port: 8083
  
spring:
  main:
    web-application-type: reactive
  application:
    name: astromyllc-api-gateway  
  #security:
  #  oauth2:
  #    client:
  #      provider:
  #        ShootingStar.issuer-uri: http://keycloak:8080/realms/ShootingStar
  #      registration:
  #        ShootingStar:
  #          client-id: astroauthauth
  #          client-secret: xw4eACct2grsmYDeFtkp4iUNyJCQO0OA
  #          authorization-grant-type: authorization_code #Client Credentials
  #          redirect-url: "{baseUrl}/login/oauth2/code/astroauthauth"

  cloud:
    compatibility-verifier:
      enabled: false


  ## Setup Service Routes
    gateway:
      routes:
        - id: setup
          uri: lb://shootingStar-setup
          predicates[0]: Path=/api/setup/**

  ## Online Application Service Routes
     # routes[1]:
        - id: online-application
          uri: lb://online-application
          predicates[0]: Path=/api/applications/**

  ## HR Service Routes
      #routes[2]:
        - id: HR
          uri: lb://HR-Service
          predicates[0]: Path=/api/hr/**

  ## Finance Service Routes
      #routes[3]:
        - id: finance
          uri: lb://finance
          predicates[0]: Path=/api/finance/**

  ## Clinic Service Routes
      #routes[4]:
        - id: clinic
          uri: lb://clinic
          predicates[0]: Path=/api/clinic/**

  ## Store-Inventory Service Routes
      #routes[5]:
        - id: stores-inventory
          uri: lb://stores-inventory
          predicates[0]: Path=/api/stores_inventory/**

  ## Academics Service Routes
      #routes[6]:
        - id: academics
          uri: lb://shootingStar-academics
          predicates[0]: Path=/api/academics/**

  ## Administration Service Routes
      #routes[7]:
        - id: administration-pta
          uri: lb://administration-pta
          predicates[0]: Path=/api/administration-pta/**

  ## Administration Service Routes
  ##spring:cloud:gateway:routes[8]:id=astroauthauth
  ##spring:cloud:gateway:routes[8]:uri=lb://astroauthauth
  ##spring:cloud:gateway:routes[8]:predicates[0]=Path=/api/**

  ## Discovery Server Routes
      #routes[8]:
        - id: discovery_server
          uri: http://localhost:8761
          predicates[0]: Path=/eureka/web
          filters[0]: SetPath=/
  
  ## Discovery Server Static Files
      #routes[9]:
        - id: discovery_server_static
          uri: http://localhost:8761
          predicates[0]: Path=/eureka/**

  ## Astro Orb Front End Static Files
      #routes[9]:
        - id:  astro_orb
          uri: http://localhost:7013
          predicates[0]: Path=/astro_orb/web
          filters[0]: SetPath=/

  ## Astro Orb Front End Static Files
      #routes[9]:
        - id: astro_orb_static
          uri: http://localhost:7013
          predicates[0]: Path=/orb/**


  sleuth:
    sampler:
      probability: 1.0


  #spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/ShootingStar

  #security.oauth2.client.provider.provider.keycloak.issuer-uri=http://localhost:8090/realms/ShootingStar
  #security.oauth2.client.registration.keycloak.client-id=astroauthauth
  #security.oauth2.client.registration.keycloak.client-secret=5Ddz2poW7lJB5U7qhInn1Rk8tO77xM6X
  #security.oauth2.client.registration.keycloak.authorization-grant-type=Client Credentials








