server:
  port: 7013
  max-http-header-size: 32KB

gateway:
  host: ${APIGATEWAY:localhost:8083}

logging:
  level:
    org:
      springframework:
        security=ERROR:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: INFO

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true


spring:
  web:
    error:
      include-stacktrace: always
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false

  codec:
    max-in-memory-size: 20MB

  application:
    name: orb_frontend

  security:
    oauth2:
      client:
        registration:
          ShootingStar:
            client-id: astroauthauth
            client-secret: ywUvVeSUVbbwgsfABUNWyKPJimFXkcwJ
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/astroauthauth"
            scope:
              - openid
              - profile
              - email
              - roles
        provider:
          ShootingStar:
            issuer-uri: "https://keycloak.astromyllc.com/realms/ShootingStar"

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true

keycloak:
  base-url: http://localhost:7013  # Change this in production
  realm: ShootingStar