server:
  port: 7013


gateway:
  host: ${APIGATEWAY:astro-api-gateway:8083}


logging:
  level:
    org:
      springframework:
        security=ERROR:
    root: ERROR
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.web.client.RestTemplate: ERROR

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
    registerWithEureka: true
    fetchRegistry: true


spring:
  web:
    error:
      include-stacktrace=always:
  mvc:
    throw-exception-if-no-handler-found=true:
  security:
    oauth2:
      client:
        registration:
          ShootingStar:
            client-id: astroauthauth
            client-secret: ywUvVeSUVbbwgsfABUNWyKPJimFXkcwJ
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/astroauthauth"
            logout-success-url: "https://keycloak.astromyllc.com/auth/realms/ShootingStar/protocol/openid-connect/auth"
            scope:
              - openid
              - profile
              - email
              - roles
        provider:
          ShootingStar:
            issuer-uri: "https://keycloak.astromyllc.com/realms/ShootingStar"

  thymeleaf:
    cache: false

  codec:
    max-in-memory-size: 20MB

  application:
    name: orb_frontend


  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


  servlet:
    multipart:
      max-file-size: 7024MB
      max-request-size: 7024MB
      enabled: true



keycloak:
  base-url: https://orb.astromyllc.com  # Change this in production
  realm: ShootingStar