server:
  port: 7013

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka

spring:
  thymeleaf:
    cache: false

  application:
    name: orb_frontend

  security:
    oauth2:
      client:
        registration:
          ShootingStar:
            client-id: astroauthauth
            client-secret: ywUvVeSUVbbwgsfABUNWyKPJimFXkcwJ
            authorization-grant-type: authorization_code
            redirect-url: http://localhost:7013/login/oauth2/code/astroauthauth
            scope:
              - openid
              - profile
              - email
              - roles
        provider:
          ShootingStar.issuer-uri: http://keycloak:8080/realms/ShootingStar

  servlet:
    multipart:
      max-file-size: 7024MB
      max-request-size: 7024MB
      enabled: true
