server:
  port: 7013


gateway:
  host: ${APIGATEWAY:astro-api-gateway:8083}


logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
        security: ERROR
        boot:
          autoconfigure: ERROR
      springframework.web.client.RestTemplate: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
    registerWithEureka: true
    fetchRegistry: true


spring:
  web:
    error:
      include-stacktrace: always
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false

  codec:
    max-in-memory-size: 20MB

  security:
    oauth2:
      client:
        registration:
          ShootingStar:
            client-id: astroauthauth
            client-secret: ywUvVeSUVbbwgsfABUNWyKPJimFXkcwJ
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/astroauthauth"
            scope:
              - openid
              - profile
              - email
              - roles
        provider:
          ShootingStar:
            issuer-uri: "https://keycloak.astromyllc.com/realms/ShootingStar"



  application:
    name: orb_frontend


  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false


  servlet:
    multipart:
      max-file-size: 7024MB
      max-request-size: 7024MB
      enabled: true

