server:
  port: 7013

gateway:
  host: ${APIGATEWAY:localhost:8083}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  thymeleaf:
    cache: false

  application:
    name: orb_frontend

  security:
    oauth2:
      client:
        registration:
          ShootingStar:
            client-id: astroauthauth
            client-secret: ywUvVeSUVbbwgsfABUNWyKPJimFXkcwJ
            authorization-grant-type: authorization_code
            redirect-url: http://localhost:7013/login/oauth2/code/astroauthauth
            scope:
              - openid
              - profile
              - email
              - roles
        provider:
          ShootingStar.issuer-uri: http://localhost:8090/realms/ShootingStar
     # resourceserver:
     #   jwt:
     #     issuer-uri: http://localhost:8080/realms/ShootingStar

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
