server:
  port: 7013

gateway:
  host: ${APIGATEWAY:localhost:8083}

logging:
  level:
    org:
      springframework:
        security=ERROR:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka


spring:
  web:
    error:
      include-stacktrace=always:
  mvc:
    throw-exception-if-no-handler-found=true:
  thymeleaf:
    cache: false

  application:
    name: orb_frontend

  security:
    oauth2:
      client:
        registration:
          ShootingStar:
            client-id: astroauthauth
            client-secret: ywUvVeSUVbbwgsfABUNWyKPJimFXkcwJ
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/astroauthauth"
            scope:
              - openid
              - profile
              - email
              - roles
        provider:
          ShootingStar:
            issuer-uri: "https://keycloak.astromyllc.com/realms/ShootingStar"


  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true
