eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

server:
  port: 0

gateway:
  host: ${APIGATEWAY:localhost:8083}

spring:
  cloud:
    compatibility-verifier:
      enabled: false

  application:
    name: shootingStar-academics

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shootingstar_academics
    username: root
    password: IdowhatIlikeIlikewhatIdo!@3
  jpa:
    hibernate:
      ddl-auto: update

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuit breaker:
    instances:
      setup:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  time limiter:
    instances:
      setup:
        timeout-duration: 3s



logging:
  level:
    org:
      springframework:
        security=ERROR:
    root: INFO
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.web.client.RestTemplate: ERROR

