spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shootingstarsetup  # URL for the created database
    username: astromyllc
    password: IdowhatIlikeIlikewhatIdo!@3
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update  # Hibernate will handle schema updates
      default_schema: public

    properties:
      hibernate:
        cache:
          use_second_level_cache: false

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: shootingStar-setup



  mail:
    # Email rate limiting configuration
    rate-limit: 5
    queue-capacity: 1000

    # Retry configuration
    max-retries: 3
    retry-delay: 5000

    host: smtp.zeptomail.com
    port: 587
    username: emailapikey
    password: "wSsVR61//x/xXfp0nmCqIuZunVtQB1j3FRx8iVOm7nT8H6/D/cc8w0KYVACvSvJNFmQ7RjIXprgoyUxV1mBY2tV8yFsACCiF9mqRe1U4J3x17qnvhDzIWW5YlBaJJYwPxwxtm2RoEMkj+g=="
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: "smtp.zeptomail.com"
        debug: false




server:
  port: 1373

gateway:
  host: ${APIGATEWAY:localhost}
  # host: ${APIGATEWAY:astro-api-gateway}  # Commented

data:
  connection: ${CONNECTION_STRING:localhost:5432}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      setup:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        authomaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      setup:
        timeout-duration: 3s




logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
        boot:
          autoconfigure: INFO
      springframework.web.client.RestTemplate: INFO


keycloak:
  address: ${KeycloakURL:https://keycloak.astromyllc.com}

