spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shootingstarsetup  # URL for the created database
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update  # Hibernate will handle schema updates

    properties:
      hibernate:
        default_schema: public
        cache:
          use_second_level_cache: false

  management:
    tracing:
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: shootingStar-setup



  mail:
    host: smtp.zeptomail.com
    port: 587
    username: emailapikey
    password: ${EMAILPASS}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            protocols: TLSv1.2
            trust: "smtp.zeptomail.com"
        debug: false

app:
  mail:
    # Email rate limiting configuration
    rate-limit: 5
    queue-capacity: 1000

    sender: noreply@astromyllc.com
    # Retry configuration
    max-retries: 3
    retry-delay: 5000




server:
  port: 1373

gateway:
  host: ${APIGATEWAY:http://localhost:8083}
  # host: ${APIGATEWAY:astro-api-gateway}  # Commented

data:
  connection: ${CONNECTION_STRING:localhost:5432}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      setup:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      setup:
        timeout-duration: 15s




logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: INFO
        boot:
          autoconfigure: INFO
        web.client.RestTemplate: INFO


keycloak:
  address: ${KeycloakURL:https://keycloak.astromyllc.com}

