spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    ##driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://postgres-shootingstarsetup:5432/shootingstarsetup
    username: astromyllc
    password: IdowhatIlikeIlikewhatIdo!@3
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
      default_schema: public
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  security:
    user:
      name: disabled
      password: disabled

  codec:
    max-in-memory-size: 20971520

  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: shootingStar-setup



  mail:
    # Email rate limiting configuration
    rate-limit: 5
    queue-capacity: 1000

    # Retry configuration
    max-retries: 3
    retry-delay: 5000

    host: smtp.zeptomail.com
    port: 587
    username: emailapikey
    password: "wSsVR61//x/xXfp0nmCqIuZunVtQB1j3FRx8iVOm7nT8H6/D/cc8w0KYVACvSvJNFmQ7RjIXprgoyUxV1mBY2tV8yFsACCiF9mqRe1U4J3x17qnvhDzIWW5YlBaJJYwPxwxtm2RoEMkj+g=="
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: "smtp.zeptomail.com"
        debug: false





server:
  port: 1373

gateway:
  host: ${APIGATEWAY:astro-api-gateway:8083}
  # host: ${APIGATEWAY:astro-api-gateway}  # Commented

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
    registerWithEureka: true
    fetchRegistry: true
  instance:
    port: 1373


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      setup:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        authomaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      setup:
        timeout-duration: 3s




logging:
  level:
    root: ERROR
    org:
      springframework:
        web: ERROR
        security: ERROR
        boot:
          autoconfigure: ERROR
      springframework.web.client.RestTemplate: ERROR

      hibernate:
        SQL: ERROR
        transaction: ERROR


keycloak:
  address: ${KeycloakURL:https://keycloak.astromyllc.com}


data:
  connection: ${CONNECTION_STRING:postgres-accommodation:5432}