server:
  port: 7310


gateway:
  host: ${APIGATEWAY:http://localhost:8083}


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

spring:
  thymeleaf:
    cache: false

  application:
    name: astro-admission-acceptance