spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/online-application
  application:
    name: online-application
  cloud:
    compatibility-verifier:
      enabled: false
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 0

gateway:
  host: ${APIGATEWAY:http://localhost:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      application:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      application:
        timeout-duration: 63s
  retry:
    instances:
      application:
        max-attempts: 1
        wait-duration: 35s



logging:
  level:
    org:
      springframework:
        security: ERROR
    root: ERROR
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    org.springframework.boot.autoconfigure: ERROR
    org.springframework.web.client.RestTemplate: ERROR
