server:
  port: 3017

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  thymeleaf:
    cache: false

  application:
    name: astro-preorder

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: astroauthauth
            client-secret: YfNJizpbcZ23UMNpayLlN4O5H1yPP7WR
            authorization-grant-type: authorization_code
            redirect-url: http://localhost:7013/login/oauth2/code/preorder
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/ShootingStar