server:
  port: 3017


gateway:
  host: ${APIGATEWAY:localhost:8083}


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: DEBUG

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

spring:
  thymeleaf:
    cache: false

  application:
    name: astro-preorder