server:
  port: 3017
  tomcat:
    max-http-form-post-size: 314572800


gateway:
  host: ${APIGATEWAY:astro-api-gateway:8083}


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: ERROR

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

spring:
  thymeleaf:
    cache: false

  application:
    name: astro-preorder

  servlet:
    multipart:
      max-file-size: 314572800
      max-request-size: 314572800