server:
  port: 3017

gateway:
  host: ${APIGATEWAY:localhost:8083}


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka

spring:
  thymeleaf:
    cache: false

  application:
    name: astro-preorder